import {Component, Input, OnInit} from '@angular/core';
import {BlogPost} from '../dtos/blog-post';

@Component({
  selector: 'app-blog-list',
  templateUrl: './blog-list.component.html',
  styleUrls: ['./blog-list.component.scss']
})
export class BlogListComponent implements OnInit {

  blogPostList: BlogPost[][];
  currentPage: number;

  constructor() {
  }

  ngOnInit() {
    this.currentPage = 0;
    this.blogPostList = [
      [
        new BlogPost('Post 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.')
      ], [
        new BlogPost('Post 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 8', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.')
      ], [
        new BlogPost('Post 9', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 11', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 12', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.')
      ], [
        new BlogPost('Post 13', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 14', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 15', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.'),
        new BlogPost('Post 16', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget auctor leo. Aliquam erat volutpat. In euismod vel dolor nec rhoncus. Vivamus dui tortor, finibus eget mi nec, luctus aliquam nisl. Suspendisse commodo malesuada arcu ut congue. Vestibulum malesuada at justo sed commodo. Duis porttitor ex id luctus malesuada. Aliquam nunc ex, luctus vitae mi a, condimentum vehicula lectus. Proin porttitor vehicula nunc, eu tempus arcu laoreet et. Nulla facilisi.')
      ]
    ];
  }

  updatePage(newPage) {
    this.currentPage = newPage;
    console.log('event emitted and method executed');
  }
}
